### ISSUE TITLE
Shouldn't link to dist

### ISSUE THREAD

**Issue by Devric** [chenjiahan/rodal#3]
Hi, first of all, awesome plugin. 

I think for NPM packages, is best not to link to the /dist folder. That should be used for bower modules. As that dist package contains all the dependencies which gets your plugin bloated, you should point the package.json to the /src index instead, since most people who is going to use npm package should have react/react dom installed for dependencies already.

**Comment by chenjiahan** [comment]
@Devric  Thanks for your suggestion , actually the dist file doesn't contain react or react-dom and the gzipped size is only 4.9KB. That's because I use libraryTarget output in webpack.config.lib.js.

```javascript
entry: "./src/rodal.js",
output: {
    path: "dist",
    filename: "rodal.js",
    libraryTarget: 'umd'
},
externals: {
    "react" : "react",
    "react-dom" : "react-dom",
    "rodal.css": 'rodal.css'
}
```

And many people exclude node_modules when building thier project, so I can't point the package.json to the src/index.
